import { Candidate } from "./types";

export const candidates: Candidate[] = [
  {
    id: "c1",
    name: "Erik Lindqvist",
    title: "Senior Frontend Developer",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL", "Jest"],
    experience: 7,
    location: "Stockholm",
    workPreference: "Remote",
    availability: "2 weeks",
    workType: "Full-time",
    domain: "FinTech",
    summary: "Seasoned frontend architect with deep React/TypeScript expertise. Led the rebuild of a major Swedish banking platform's customer portal, improving performance by 40%. Passionate about design systems and accessibility.",
  },
  {
    id: "c2",
    name: "Anna Bergström",
    title: "Full Stack Engineer",
    skills: ["Node.js", "React", "PostgreSQL", "Docker", "Redis", "AWS"],
    experience: 5,
    location: "Gothenburg",
    workPreference: "Hybrid",
    availability: "1 month",
    workType: "Full-time",
    domain: "E-commerce",
    summary: "Versatile full stack developer who built scalable e-commerce platforms handling 50K+ daily transactions. Strong in both frontend UX and backend API design with a focus on performance optimization.",
  },
  {
    id: "c3",
    name: "Mohammed Al-Hassan",
    title: "Data Engineer",
    skills: ["Python", "Apache Spark", "Airflow", "SQL", "Kafka", "dbt"],
    experience: 4,
    location: "Malmö",
    workPreference: "Remote",
    availability: "Immediately",
    workType: "Contract",
    domain: "HealthTech",
    summary: "Data pipeline specialist experienced in processing large-scale healthcare datasets. Built GDPR-compliant ETL pipelines processing 2TB+ daily. Certified in both AWS and Azure data services.",
  },
  {
    id: "c4",
    name: "Sofia Johansson",
    title: "DevOps Engineer",
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD", "Prometheus", "Go"],
    experience: 6,
    location: "Stockholm",
    workPreference: "Hybrid",
    availability: "1 month",
    workType: "Full-time",
    domain: "SaaS",
    summary: "Infrastructure expert who reduced deployment times by 80% through automated CI/CD pipelines. Manages multi-region Kubernetes clusters serving 1M+ users. AWS Solutions Architect certified.",
  },
  {
    id: "c5",
    name: "Lisa Eriksson",
    title: "UX Designer & Frontend Developer",
    skills: ["Figma", "React", "CSS", "User Research", "Prototyping", "Storybook"],
    experience: 3,
    location: "Uppsala",
    workPreference: "Remote",
    availability: "2 weeks",
    workType: "Freelance",
    domain: "EdTech",
    summary: "Design-minded developer bridging the gap between UX and engineering. Created award-winning interfaces for Swedish EdTech platforms. Specializes in component libraries and design system implementation.",
  },
  {
    id: "c6",
    name: "Karl Nilsson",
    title: "Backend Developer",
    skills: ["Java", "Spring Boot", "Kafka", "Microservices", "Oracle", "REST"],
    experience: 9,
    location: "Stockholm",
    workPreference: "Onsite",
    availability: "3 months",
    workType: "Full-time",
    domain: "Banking",
    summary: "Enterprise backend veteran with extensive experience in Swedish banking systems. Architected microservices handling millions of daily transactions with 99.99% uptime. Expert in regulatory compliance and security.",
  },
  {
    id: "c7",
    name: "Fatima Öberg",
    title: "ML Engineer",
    skills: ["Python", "TensorFlow", "PyTorch", "MLOps", "Scikit-learn", "Docker"],
    experience: 4,
    location: "Linköping",
    workPreference: "Remote",
    availability: "Immediately",
    workType: "Contract",
    domain: "AI/ML",
    summary: "Applied ML engineer specializing in NLP and recommendation systems. Deployed production models serving 500K+ predictions daily. Published research on transformer architectures for Swedish language processing.",
  },
  {
    id: "c8",
    name: "Oscar Pettersson",
    title: "Mobile Developer",
    skills: ["React Native", "TypeScript", "Firebase", "Redux", "iOS", "Android"],
    experience: 5,
    location: "Gothenburg",
    workPreference: "Hybrid",
    availability: "2 weeks",
    workType: "Full-time",
    domain: "Logistics",
    summary: "Cross-platform mobile specialist who built logistics apps used by 10K+ drivers across Scandinavia. Expert in offline-first architecture and real-time tracking with WebSockets and Firebase.",
  },
  {
    id: "c9",
    name: "Ingrid Svensson",
    title: "Cloud Architect",
    skills: ["AWS", "Azure", "Terraform", "Serverless", "Security", "Cost Optimization"],
    experience: 8,
    location: "Stockholm",
    workPreference: "Remote",
    availability: "1 month",
    workType: "Full-time",
    domain: "Cybersecurity",
    summary: "Multi-cloud architect with deep security expertise. Designed zero-trust architectures for Swedish defense contractors. Reduced cloud costs by 45% through optimization and reserved capacity planning.",
  },
  {
    id: "c10",
    name: "Anders Björk",
    title: "QA Automation Engineer",
    skills: ["Cypress", "Selenium", "Jest", "K6", "API Testing", "CI/CD"],
    experience: 4,
    location: "Malmö",
    workPreference: "Hybrid",
    availability: "Immediately",
    workType: "Full-time",
    domain: "InsurTech",
    summary: "Test automation expert who built comprehensive testing frameworks covering unit, integration, and e2e testing. Reduced production bugs by 70% through shift-left testing practices and performance testing.",
  },
];
